#
# Copyright (c) 2019, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
---
# Supported Locale POSIX names
# As defined on saspedia/List_of_locales_supported_by_Viya_3.3
languages_list:
   - af_ZA
   - sq_AL
   - ar_DZ
   - ar_BH
   - ar_IN
   - ar_IQ
   - ar_JO
   - ar_KW
   - ar_LB
   - ar_LY
   - ar_MA
   - ar_OM
   - ar_QA
   - ar_SA
   - ar_SD
   - ar_SY
   - ar_TN
   - ar_AE
   - ar_YE
   - bn_IN
   - bs_BA
   - bg_BG
   - be_BY
   - ca_ES
   - zh_CN
   - zh_HK
   - zh_MO
   - zh_SG
   - zh_TW
   - kw_GB
   - hr_BA
   - hr_HR
   - cs_CZ
   - da_DK
   - nl_BE
   - nl_NL
   - en_AU
   - en_BE
   - en_BW
   - en_CA
   - en_CB
   - en_HK
   - en_IN
   - en_IE
   - en_JM
   - en_MT
   - en_NZ
   - en_PH
   - en_SG
   - en_ZA
   - en_GB
   - en_US
   - en_ZW
   - et_EE
   - fo_FO
   - fi_FI
   - fr_BE
   - fr_CA
   - fr_FR
   - fr_LU
   - fr_CH
   - de_AT
   - de_DE
   - de_LI
   - de_LU
   - de_CH
   - el_CY
   - el_GR
   - kl_GL
   - he_IL
   - hi_IN
   - hu_HU
   - is_IS
   - id_ID
   - ga_IE
   - it_IT
   - it_CH
   - ja_JP
   - ko_KR
   - lv_LV
   - lt_LT
   - mk_MK
   - mt_MT
   - eu_ES
   - mr_IN
   - nb_NO
   - nn_NO
   - no_NO
   - fa_IN
   - fa_IR
   - pl_PL
   - pt_BR
   - pt_PT
   - ro_RO
   - ru_RU
   - ru_UA
   - sr_BA
   - sr_ME
   - sr_RS
   - kk_KZ
   - sh_BA
   - sh_ME
   - sh_RS
   - sk_SK
   - sl_SI
   - es_AR
   - es_BO
   - es_CL
   - es_CO
   - es_CR
   - es_DO
   - es_EC
   - es_SV
   - es_GT
   - es_HN
   - es_MX
   - es_NI
   - es_PA
   - es_PR
   - es_ES
   - es_US
   - es_UY
   - es_VE
   - sv_SE
   - ta_IN
   - te_IN
   - th_TH
   - tl_PH
   - tr_TR
   - uk_UA
   - vi_VN

   

