#
# Copyright (c) 2019-2020, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
---
- import_tasks: pre.pause.yml
- import_tasks: pre.shell_check.yml
- import_tasks: pre.os_version_check.yml
- import_tasks: pre.third_party_check.yml
- import_tasks: pre.memory_check.yml
- import_tasks: pre.cpu_check.yml
- import_tasks: pre.storage_check.yml
- import_tasks: pre.hostname_check.yml
- import_tasks: pre.short_hostname_check.yml
- import_tasks: pre.yum_cache_config.yml
- import_tasks: pre.required_packages_config.yml
- import_tasks: pre.start_services.yml
- import_tasks: pre.ssh_maxstartups_config.yml
- import_tasks: pre.ssh_clientaliveinterval_check.yml
- import_tasks: pre.max_os_tasks_config.yml
- import_tasks: pre.user_and_group_config.yml
- import_tasks: pre.sudo_access_check.yml
## ssl and proxy check tasks should not be used.  Future enhancements.
#- import_tasks: pre.ssl_check.yml
#- import_tasks: pre.proxy_check.yml
- import_tasks: pre.selinux_config.yml
- import_tasks: pre.ulimit_config.yml
- import_tasks: pre.os_firewall_config.yml
- import_tasks: pre.ntp_config.yml
- import_tasks: pre.network_and_bandwidth_check.yml
- import_tasks: pre.timeouts_config.yml
- import_tasks: pre.swappiness_config.yml
- import_tasks: pre.performance_config.yml
- import_tasks: pre.locale_check.yml
- import_tasks: pre.other.yml
