####################################################################
#### viya-services-restart.yml                                  ####
####################################################################
#### Author: SAS Institute Inc.                                 ####
####################################################################
#
# Copyright (c) 2019-2020, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
---
- import_playbook: viya-services-stop.yml
- import_playbook: viya-services-start.yml
- import_playbook: viya-services-status.yml
