####################################################################
#### viya-services-vars.yml                                     ####
####################################################################
#### Author: SAS Institute Inc.                                 ####
####################################################################
#
# Copyright (c) 2019-2020, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
---
svs_label: 3.5.20201204
#########################################
# Variables used in playbooks
#########################################
consul_retry_count: 2                 #retry counter
enable_pause_timer: true              #pause timer
enable_stray_cleanup: false           #stray processes cleanup
enable_svs_alternative: false         #start/stop microservices using alternative script
log_diskspace_minimum: 2097152000     #2GB
stop_pause_timer: 10                  #seconds
stray_process_count: 30               #0: list all
svas_delay_timer: 2                   #seconds
svas_retry_count: 3                   #retry counter
url_link: https                       #default https
